import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Suxz Bootcamp",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<link
				rel="icon"
				href="https://logos-world.net/wp-content/uploads/2023/12/F1-Logo.png"
			/>
			<body className={inter.className}>{children}</body>
		</html>
	);
}
